In [1]:
from main import *

In [2]:
ti = pd.read_csv('processed_data/msci_india/historical.csv')
ti_sc = pd.read_csv('processed_data/msci_sc_india/historical.csv')

In [4]:
ti['date'] = pd.to_datetime(ti['date']).dt.date
ti_sc['date'] = pd.to_datetime(ti_sc['date']).dt.date

In [6]:
query_date = dt.date(2026, 3, 31)

In [8]:
ti[ti['date'] == query_date].reset_index(drop=True)
ti_sc[ti_sc['date'] == query_date].reset_index(drop=True)

,date,rank,ticker,name,sector,weight
0,2026-03-31,1.00,HDFCBANK,HDFC BANK LTD,Financials,6.95
1,2026-03-31,2.00,RELIANCE,RELIANCE INDUSTRIES LTD,Energy,6.67
2,2026-03-31,3.00,ICICIBANK,ICICI BANK LTD,Financials,5.33
3,2026-03-31,4.00,BHARTIARTL,BHARTI AIRTEL LTD,Communication,3.73
4,2026-03-31,5.00,INFY,INFOSYS LTD,Information Technology,3.31
...,...,...,...,...,...,...
159,2026-03-31,160.00,BALKRISIND,BALKRISHNA INDUSTRIES LTD,Consumer Discretionary,0.13
160,2026-03-31,161.00,KALYANKJIL,KALYAN JEWELLERS INDIA LTD,Consumer Discretionary,0.13
161,2026-03-31,162.00,TATACOMM,TATA COMMUNICATIONS LTD,Communication,0.13
162,2026-03-31,163.00,OFSS,ORACLE FINANCIAL SERVICES SOFTWARE,Information Technology,0.12
163,2026-03-31,164.00,RVNL,RAIL VIKAS NIGAM LTD,Industrials,0.11

,date,rank,ticker,name,sector,weight
0,2026-03-31,1.00,FEDERALBNK,FEDERAL BANK LTD,Financials,1.65
1,2026-03-31,2.00,MFSL,MAX FINANCIAL SERVICES LTD,Financials,1.44
2,2026-03-31,3.00,EMBASSY,EMBASSY OFFICE PARKS REIT UNITS,Real Estate,1.25
3,2026-03-31,4.00,COFORGE,COFORGE LTD,Information Technology,1.24
4,2026-03-31,5.00,LAURUSLABS,LAURUS LABS LTD,Health Care,1.22
...,...,...,...,...,...,...
470,2026-03-31,471.00,SURYAROSNI,SURYA ROSHNI LTD,Materials,0.04
471,2026-03-31,472.00,MIDHANI,MISHRA DHATU NIGAM LTD,Materials,0.04
472,2026-03-31,473.00,BLUEJET,BLUE JET HEALTHCARE LTD,Health Care,0.04
473,2026-03-31,474.00,RAJESHEXPO,RAJESH EXPORTS LTD,Consumer Discretionary,0.00
474,2026-03-31,475.00,532425,GENUS PRIME INFRA LTD,Real Estate,0.00

In [11]:
qt.view(ti[ti['date'] == query_date].reset_index(drop=True))
qt.view(ti_sc[ti_sc['date'] == query_date].reset_index(drop=True))

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…